# Generated by Django 4.0.6 on 2022-07-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Организация клиента')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_organizations', to='api.client', verbose_name='Название клиента')),
            ],
            options={
                'verbose_name': 'Организация клиента',
                'verbose_name_plural': 'Организации клиента',
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(verbose_name='№')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('service', models.CharField(max_length=200, verbose_name='Услуга')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.client', verbose_name='Имя клиента')),
                ('client_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.clientorganization', verbose_name='Имя организации клиента')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['client_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientorganization',
            constraint=models.UniqueConstraint(fields=('client_name', 'name'), name='unique_client_organizations'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('client_org', 'order_number'), name='unique_bill_client_org'),
        ),
    ]
