# Generated by Django 4.0.6 on 2022-07-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='fraud_score',
            field=models.FloatField(default=1, verbose_name='Случайное значение'),
            preserve_default=False,
        ),
    ]
