# Generated by Django 4.0.6 on 2022-07-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bill_fraud_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='service_class',
            field=models.PositiveIntegerField(default=1, verbose_name='Класс сервиса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='service_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Название сервиса'),
            preserve_default=False,
        ),
    ]
