# Generated by Django 4.0.6 on 2022-07-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bill_service_class_bill_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorganization',
            name='fraud_weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Мошенничество'),
        ),
    ]
